version: "3.4"

services:
  raidbot:
    build:
      context: ./pokemonraidbot/
    ports:
      - 8088:80
    depends_on:
      - raidbot-db
    restart: always
    volumes:
      - ./PokemonRaidBot/config/:/var/www/html/config/
      - ./PokemonRaidBot/access/:/var/www/html/access/
      - ./PokemonRaidBot/custom/:/var/www/html/custom/
      - ./tg-logs/:/var/log/tg-bots/
    environment:
      CRON_USER_1: ${CRON_USER_1}
      CRON_SCHEDULE_1: ${CRON_SCHEDULE_1}
      CRON_COMMAND_1: ${CRON_COMMAND_1}
      CRON_USER_2: ${CRON_USER_2}
      CRON_SCHEDULE_2: ${CRON_SCHEDULE_2}
      CRON_COMMAND_2: ${CRON_COMMAND_2}
      TEMPLATE_PHP_INI: production
      PHP_INI_EXTENSION: gd

  raidbot-db:
    image: mariadb:10.3
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./raidbot-db/:/var/lib/mysql/
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: raidbot
      MYSQL_USER: raidbot
      MYSQL_PASSWORD: raidbot
